### ISSUE TITLE
support for gatk v4

### ISSUE THREAD

**Issue by joshuamschmidt** [rdemolgen/SavvySuite#24]
While required version of GATK is not stated, requirement for GenomeAnalysisTK.jar means that gatk version 3 required. Would be great to enable the use of GATK 4.

**Comment by exeter-matthew-wakeling** [comment]
Hi. I just tested compiling SavvySuite against GATK 4 and testing against a set of WGS data. It worked fine, and gave identical results to GATK 3. SavvySuite doesn't actually use any GATK stuff, just the libraries that GATK also relies on. I'll adjust the instructions to indicate that GATK 4 is fine.

Thanks for the suggestion. Matthew
