### ISSUE TITLE
Compilation Errors and Warnings in SavvyCNVJointCaller.java

### ISSUE THREAD

**Issue by Redwan468001** [rdemolgen/SavvySuite#25]
While attempting to compile the code using the javac *.java command, two errors were encountered at lines 131 and 132 within the SavvyCNVJointCaller.java file, along with several compilation warnings. It shows- 

SavvyCNVJointCaller.java:131: error: method logProbDel in class SavvyCNV cannot be applied to given types;
                                        delProb[i] = SavvyCNV.logProbDel(depths[i].getVal(), depths[i].getStddev(), minProb, mosaic);
                                                             ^
  required: double,double,boolean
  found: double,double,double,boolean
  reason: actual and formal argument lists differ in length
SavvyCNVJointCaller.java:132: error: method logProbDup in class SavvyCNV cannot be applied to given types;
                                        dupProb[i] = SavvyCNV.logProbDup(depths[i].getVal(), depths[i].getStddev(), minProb, mosaic);
                                                             ^
  required: double,double,boolean
  found: double,double,double,boolean
  reason: actual and formal argument lists differ in length

Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: CoverageOffTarget.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

Ignoring these warnings may allow us to run the code; however, it raises concerns about potential compatibility issues and code reliability.

**Comment by exeter-matthew-wakeling** [comment]
Thanks for pointing this out. I have fixed the compile errors, which were due to an upgrade in SavvyCNV without checking to ensure this was compatible with SavvyCNVJointCaller. The warnings have been fixed as well, though these were not anything to worry about.
