### ISSUE TITLE
SelectControlSamples fails due to java.io.StreamCorruptedException

### ISSUE THREAD

**Issue by TacModd** [rdemolgen/SavvySuite#26]
Hi there, no matter what I attempt I always run into a StreamCorruptedException when I run SelectControlSamples. The invalid code is always 1F8B0800, which I think implies the stream is gzipped when it shouldn't be? I don't suppose you have encountered this issue?

```
$ java SelectControlSamples -d 800 test_bins/*.coverageBinner >summary_file

...

Normalising
Average reads in each bucket: 3.6185759178152446
Number of genome chunks: 6469
Performed SVD in 23ms
Performed inverse in 18ms
Exception in thread "main" java.io.StreamCorruptedException: invalid stream header: 1F8B0800
	at java.base/java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:936)
	at java.base/java.io.ObjectInputStream.<init>(ObjectInputStream.java:375)
	at SelectControlSamples.calculateSampleVector(SelectControlSamples.java:358)
	at SelectControlSamples.main(SelectControlSamples.java:254)
```

**Comment by TacModd** [comment]
Ah, I've figured out the problem, it seems my coverage bins were corrupted without me realising. Apologies for the noise! I'll close this issue

**Comment by exeter-matthew-wakeling** [comment]
No, you're right. I missed a place in SelectControlSamples when I changed the format of CoverageBinner files. The new file format is gzipped. Please ensure you read the README for a full message about the consequences of the format update. I apologise for breaking this tool. I will fix it as soon as I can. However, I'm full of a cold right now, so it might be a day or so.

**Comment by exeter-matthew-wakeling** [comment]
Turns out I actually fixed this a while ago and never got round to checking it in. My most sincere apologies. It should now be all fixed. Please let me know if there are any further issues.
