### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by questcof** [rdemolgen/SavvySuite#27]
Hi Matthew,

Thank you for making and sharing this tool!

I am a new user trying to run the tool for the first time on a HPC. After I set the class path as instructed in the README, I then try to compile only to be met with an error message. Any advice is greatly appreciated!

$ export CLASSPATH=/path/to/my/gatk/gatk-4.5.0.0/gatk-package-4.5.0.0-local.jar:/SavvySuite-1.0

$ javac *.java

VariantArray.java:17: error: cannot access VariantContext
	@SuppressWarnings("deprecation") public VariantArray(List<String> vcfSampleNames, VariantContext context) {
	                                                                                  ^
  bad class file: /path/to/my/gatk/gatk-4.5.0.0/gatk-package-4.5.0.0-local.jar(/htsjdk/variant/variantcontext/VariantContext.class)
    class file has wrong version 61.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
SavvyHomozygosity.java:200: error: cannot access SAMRecordIterator
		private SAMRecordIterator iter;
		        ^
  bad class file: /path/to/my/gatk/gatk-4.5.0.0/gatk-package-4.5.0.0-local.jar(/htsjdk/samtools/SAMRecordIterator.class)
    class file has wrong version 61.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
SavvyHomozygosity.java:201: error: cannot access SamReader
		private SamReader in;
		        ^
  bad class file: /path/to/my/gatk/gatk-4.5.0.0/gatk-package-4.5.0.0-local.jar(/htsjdk/samtools/SamReader.class)
    class file has wrong version 61.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
SavvyHomozygosity.java:203: error: cannot access SAMRecord
		private LinkedList<SAMRecord> records;
		                   ^
  bad class file: /path/to/my/gatk/gatk-4.5.0.0/gatk-package-4.5.0.0-local.jar(/htsjdk/samtools/SAMRecord.class)
    class file has wrong version 61.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
SavvyHomozygosity.java:204: error: cannot find symbol
		private SAMRecord lastRecord = null;
		        ^
  symbol:   class SAMRecord
  location: class BamReader
SavvySharedHaplotypes.java:160: error: cannot find symbol
		private SAMRecordIterator iter;
		        ^
  symbol:   class SAMRecordIterator
  location: class BamReader
SavvySharedHaplotypes.java:161: error: cannot find symbol
		private SamReader in;
		        ^
  symbol:   class SamReader
  location: class BamReader
SavvySharedHaplotypes.java:163: error: cannot find symbol
		private LinkedList<SAMRecord> records;
		                   ^
  symbol:   class SAMRecord
  location: class BamReader
SavvySharedHaplotypes.java:164: error: cannot find symbol
		private SAMRecord lastRecord = null;
		        ^
  symbol:   class SAMRecord
  location: class BamReader
9 errors

Thank you in advance,
Becky

**Comment by exeter-matthew-wakeling** [comment]
Hi Becky.

You're using Java 11 on your computer to try to compile SavvySuite. It's completely compatible with that version of Java, but the version of GATK you are using is not - it requires Java version 17 or above. To fix this, you can either upgrade to a newer version of Java, or download an older version of GATK. This particular error is completely out of my control, and nothing to do with SavvySuite itself. Hope that helps.

Matthew

**Comment by questcof** [comment]
Hi Matthew,

Thank you for explaining that, really helpful. I am now using GATK3.7 with Java 8, which I believe is compatible.

Now when I go to compile I get "Note: SavvyVcfHomozygosity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details."

And so running:

$ javac -Xlint:deprecation *.java

Gives:

SavvyVcfHomozygosity.java:119: warning: [deprecation] getChr() in Feature has been deprecated
			String contextChr = context.getChr();
			                           ^
SavvyVcfHomozygosity.java:182: warning: [deprecation] getChr() in Feature has been deprecated
							if (NUM_CHROM.matcher(context.getChr()).matches()) {
							                             ^
SavvyVcfHomozygosity.java:184: warning: [deprecation] getChr() in Feature has been deprecated
								int chrInt = Integer.parseInt(context.getChr());
								                                     ^
SavvyVcfHomozygosity.java:190: warning: [deprecation] getChr() in Feature has been deprecated
							if (NUM_CHROM.matcher(context.getChr()).matches()) {
							                             ^
SavvyVcfHomozygosity.java:192: warning: [deprecation] getChr() in Feature has been deprecated
								int chrInt = Integer.parseInt(context.getChr());
								                                     ^
SavvyVcfHomozygosity.java:209: warning: [deprecation] getChr() in Feature has been deprecated
								if (NUM_CHROM.matcher(context.getChr()).matches()) {
								                             ^
SavvyVcfHomozygosity.java:212: warning: [deprecation] getChr() in Feature has been deprecated
										int chrInt = Integer.parseInt(context.getChr());
										                                     ^
SavvyVcfHomozygosity.java:220: warning: [deprecation] getChr() in Feature has been deprecated
								if (NUM_CHROM.matcher(context.getChr()).matches()) {
								                             ^
SavvyVcfHomozygosity.java:223: warning: [deprecation] getChr() in Feature has been deprecated
										int chrInt = Integer.parseInt(context.getChr());
										                                     ^
9 warnings

Sorry to bother you again but I am really interested in using SavvyCNV, any ideas where I am going wrong this time?

Thank you again in advance,
Becky

**Comment by exeter-matthew-wakeling** [comment]
Yes, those two are compatible. Regarding that warning, nothing has gone wrong. I will change the code so that it doesn't give the warning, however the cause is that I have used the "getChr()" method from the GATK library - it has been replaced with getContig() in more recent versions of the library, and the getChr() method has been marked as obsolete, but I'm continuing to use it because it allows greater backwards-compatibility with older versions of the library.

You successfully compiled the software, and can now use it. I hope it produces some good results for you.

**Comment by questcof** [comment]
Great, thank you so much. I hope it does too! Although I'm still having some issues.

I can create the summary files using the given command
$ java -Xmx1g CoverageBinner sample.bam >sample.coverageBinner

But if I try to provide -d 200000 as an option like so:

java -Xmx4g CoverageBinner -d 200000 /path/to/my/sample.bam > sample.coverageBinner

It throws an Exception error:
Exception in thread "main" htsjdk.samtools.util.RuntimeIOException: java.io.FileNotFoundException: -d (No such file or directory)

The same thing happens at the next step when running SavvyCNV if I try to add any additional options. 

Any ideas? Thanks again!

**Comment by exeter-matthew-wakeling** [comment]
That's weird. Could you post the whole error message, including all the lines after what you posted above please? That'll help me work out what is going wrong. I just tested and it works for me. Is there any chance you are using an older version of CoverageBinner than the latest version here on GitHub? When you run CoverageBinner without the "-d 200000" option, what size output file do you get?

**Comment by questcof** [comment]
Sure I can, thanks Matthew.

Full error with -d is:

Exception in thread "main" htsjdk.samtools.util.RuntimeIOException: java.io.FileNotFoundException: -d (No such file or directory)
	at htsjdk.samtools.FileInputResource$1.make(SamInputResource.java:222)
	at htsjdk.samtools.FileInputResource$1.make(SamInputResource.java:216)
	at htsjdk.samtools.util.Lazy.get(Lazy.java:24)
	at htsjdk.samtools.FileInputResource.asUnbufferedSeekableStream(SamInputResource.java:254)
	at htsjdk.samtools.FileInputResource.asUnbufferedInputStream(SamInputResource.java:259)
	at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:306)
	at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:169)
	at CoverageBinner.main(CoverageBinner.java:20)
Caused by: java.io.FileNotFoundException: -d (No such file or directory)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at htsjdk.samtools.seekablestream.SeekableFileStream.<init>(SeekableFileStream.java:47)
	at htsjdk.samtools.FileInputResource$1.make(SamInputResource.java:220)
	... 7 more

Without -d the files are ~ 80M

**Comment by exeter-matthew-wakeling** [comment]
Yep, you definitely have an old version of CoverageBinner there. The new version of CoverageBinner (uploaded to Github on the 15th of November) added the "-d" option (and others) and produces much smaller output files due to using fancy compression methods. You should update (or re-download) SavvyCNV from GitHub, re-compile, and try again.

**Comment by questcof** [comment]
That has worked, thank you so much for your help. Have a great evening!
