### ISSUE TITLE
CoverageBinner seems to run and then does not produce output file

### ISSUE THREAD

**Issue by becky-genomics** [rdemolgen/SavvySuite#28]
Hi, I'm trying to run CoverageBinner on some WES bam files.

`$ java CoverageBinner /data/sample.bam output/sample.coverageBinner`

The process seems to run fine for a time and then spits out a bunch of mess which to me looks like random characters.

`Processed 10000000 reads, resized 16 times, now on chr1:148129416
Processed 20000000 reads, resized 29 times, now on chr10:26566907
Processed 30000000 reads, resized 44 times, now on chr11:29275477
Processed 40000000 reads, resized 59 times, now on chr12:19403943
Processed 50000000 reads, resized 67 times, now on chr13:53205361
Processed 60000000 reads, resized 78 times, now on chr15:40955567
Processed 70000000 reads, resized 96 times, now on chr16:85822153
Processed 80000000 reads, resized 127 times, now on chr18:44668485
Processed 90000000 reads, resized 154 times, now on chr2:33086391
Processed 100000000 reads, resized 159 times, now on chr2:202913706
Processed 110000000 reads, resized 179 times, now on chr21:44994495
Processed 120000000 reads, resized 198 times, now on chr3:110727054
Processed 130000000 reads, resized 214 times, now on chr4:70679823
Processed 140000000 reads, resized 232 times, now on chr5:76041637
Processed 150000000 reads, resized 247 times, now on chr6:31382954
Processed 160000000 reads, resized 261 times, now on chr7:10941086
Processed 170000000 reads, resized 272 times, now on chr8:1873128
Processed 180000000 reads, resized 294 times, now on chr9:21997974
Processed 190000000 reads, resized 312 times, now on chrX:116173093
??srjava.util.LinkedHashMap4?N\l??Z
                                   accessOrderxrjava.util.HashMap???`?F
loadFactorI	thresholdxp?@??tchr1ur[IM?`&v겥xp??
                                                   ?` and so on....

The output file is never created.

I'm running this in an env with Java v17.0.10, Python v3.12.5, and had no issues compiling SavvySuite. Any idea what's going on?

Many thanks in advance!

**Comment by exeter-matthew-wakeling** [comment]
Hi Becky. As stated in the documentation, the stdout from CoverageBinner should be redirected to the file you want to create, like this:

java CoverageBinner input.bam >output.coverageBinner

Matthew

________________________________
From: becky-genomics ***@***.***>
Sent: Thursday, September 5, 2024 3:55:43 pm
To: rdemolgen/SavvySuite ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rdemolgen/SavvySuite] CoverageBinner seems to run and then does not produce output file (Issue #28)

CAUTION: This email originated from outside of the organisation. Do not click links or open attachments unless you recognise the sender and know the content is safe.


Hi, I'm trying to run CoverageBinner on some WES bam files.

$ java CoverageBinner /data/sample.bam output/sample.coverageBinner

The process seems to run fine for a time and then spits out a bunch of mess which to me looks like random characters.

Processed 10000000 reads, resized 16 times, now on chr1:148129416 Processed 20000000 reads, resized 29 times, now on chr10:26566907 Processed 30000000 reads, resized 44 times, now on chr11:29275477 Processed 40000000 reads, resized 59 times, now on chr12:19403943 Processed 50000000 reads, resized 67 times, now on chr13:53205361 Processed 60000000 reads, resized 78 times, now on chr15:40955567 Processed 70000000 reads, resized 96 times, now on chr16:85822153 Processed 80000000 reads, resized 127 times, now on chr18:44668485 Processed 90000000 reads, resized 154 times, now on chr2:33086391 Processed 100000000 reads, resized 159 times, now on chr2:202913706 Processed 110000000 reads, resized 179 times, now on chr21:44994495 Processed 120000000 reads, resized 198 times, now on chr3:110727054 Processed 130000000 reads, resized 214 times, now on chr4:70679823 Processed 140000000 reads, resized 232 times, now on chr5:76041637 Processed 150000000 reads, resized 247 times, now on chr6:31382954 Processed 160000000 reads, resized 261 times, now on chr7:10941086 Processed 170000000 reads, resized 272 times, now on chr8:1873128 Processed 180000000 reads, resized 294 times, now on chr9:21997974 Processed 190000000 reads, resized 312 times, now on chrX:116173093 ??srjava.util.LinkedHashMap4?N\l??Z accessOrderxrjava.util.HashMap????F
loadFactorI thresholdxp?@??tchr1ur[IM?&v겥xp?? ? and so on....

The output file is never created.

I'm running this in an env with Java v17.0.10, Python v3.12.5, and had no issues compiling SavvySuite. Any idea what's going on?

Many thanks in advance!

**Comment by exeter-matthew-wakeling** [comment]
Hi Becky. Hopefully this solved your issue. I'm going to close it now, please feel free to raise it again if there is still a problem.
