### ISSUE TITLE
What is a "reasonable number of samples" for SavvyCNV?

### ISSUE THREAD

**Issue by CarlosBorroto** [rdemolgen/SavvySuite#6]
> This software analyses the read depth of off-target reads to detect CNVs. It requires a reasonable number of samples sequenced using the same method. (Don't mix samples sequenced using different methods - it won't work well.)

Is there an estimated number of samples needed for the `SavvyCNV` method to work well?

**Comment by exeter-matthew-wakeling** [comment]
You need at least six or the software will not run, probably fifteen before the results become reasonably reliable, preferably more along the lines of 50. I have run it with 1000 without trouble.

**Comment by CarlosBorroto** [comment]
Thanks!
