### ISSUE TITLE
Help with Jama Library

### ISSUE THREAD

**Issue by MariaAvylak** [rdemolgen/SavvySuite#7]
Hello,
I am trying to use SavvySuite, but as I am a newbie at this, I don't understand where do I need to install Jama library.
When I run the following command    `javac *.java`
my error is :

`SavvyCNV.java:207: error: package Jama does not exist
		Jama.Matrix A = new Jama.Matrix(aArray);
		    ^
SavvyCNV.java:207: error: package Jama does not exist
		Jama.Matrix A = new Jama.Matrix(aArray);
		                        ^
`

Thank you in advance.

**Comment by exeter-matthew-wakeling** [comment]
The README gives more information, but you need to download the GATK jar from the Broad Institute, then you need your Java classpath to include it and the location of the SavvySuite code. For example:

export CLASSPATH=/path/to/GenomeAnalysisTK.jar:/path/to/SavvySuite/directory

Substitute the actual location of the GATK jar and where you have downloaded the SavvySuite software. Once you have done this, then you can run javac to compile, and run the analysis.
